services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-80}:80"
    # No volume mounts to avoid Windows path issues
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - RAILWAY_STATIC_URL=${RAILWAY_STATIC_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - PORT=${PORT:-80}
    networks:
      - tspi_network

networks:
  tspi_network:
    driver: bridge

volumes:
  mysql_data: 