-- Drop existing table if it exists
DROP TABLE IF EXISTS `members_information`;

-- Create complete members_information table with all form inputs mapped
CREATE TABLE `members_information` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `branch` VARCHAR(100) NOT NULL,
  `cid_no` VARCHAR(50) NOT NULL,
  `center_no` VARCHAR(50) DEFAULT NULL,
  `plans` JSON DEFAULT NULL,
  `classification` JSON DEFAULT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(100) DEFAULT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(10) DEFAULT NULL,
  `civil_status` VARCHAR(20) DEFAULT NULL,
  `birthdate` DATE NOT NULL,
  `age` INT NOT NULL DEFAULT 0,
  `birth_place` VARCHAR(100) DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cell_phone` VARCHAR(20) DEFAULT NULL,
  `contact_no` VARCHAR(20) DEFAULT NULL,
  `nationality` VARCHAR(50) DEFAULT NULL,
  `id_number` VARCHAR(50) DEFAULT NULL,
  `other_valid_ids` JSON DEFAULT NULL,
  `mothers_maiden_last_name` VARCHAR(100) DEFAULT NULL,
  `mothers_maiden_first_name` VARCHAR(100) DEFAULT NULL,
  `mothers_maiden_middle_name` VARCHAR(100) DEFAULT NULL,
  `present_address` VARCHAR(255) DEFAULT NULL,
  `present_region_text` VARCHAR(100) DEFAULT NULL,
  `present_province_text` VARCHAR(100) DEFAULT NULL,
  `present_city_text` VARCHAR(100) DEFAULT NULL,
  `present_barangay_text` VARCHAR(100) DEFAULT NULL,
  `present_zip_code` VARCHAR(20) DEFAULT NULL,
  `permanent_address` VARCHAR(255) DEFAULT NULL,
  `permanent_region_text` VARCHAR(100) DEFAULT NULL,
  `permanent_province_text` VARCHAR(100) DEFAULT NULL,
  `permanent_city_text` VARCHAR(100) DEFAULT NULL,
  `permanent_barangay_text` VARCHAR(100) DEFAULT NULL,
  `permanent_zip_code` VARCHAR(20) DEFAULT NULL,
  `home_ownership` VARCHAR(50) DEFAULT NULL,
  `length_of_stay` INT DEFAULT NULL,
  `primary_business` VARCHAR(255) DEFAULT NULL,
  `years_in_business` INT DEFAULT NULL,
  `business_address` TEXT DEFAULT NULL,
  `business_region_text` VARCHAR(100) DEFAULT NULL,
  `business_province_text` VARCHAR(100) DEFAULT NULL,
  `business_city_text` VARCHAR(100) DEFAULT NULL,
  `business_barangay_text` VARCHAR(100) DEFAULT NULL,
  `business_zip_code` VARCHAR(20) DEFAULT NULL,
  `other_income_source_1` VARCHAR(255) DEFAULT NULL,
  `other_income_source_2` VARCHAR(255) DEFAULT NULL,
  `other_income_source_3` VARCHAR(255) DEFAULT NULL,
  `other_income_source_4` VARCHAR(255) DEFAULT NULL,
  `spouse_name` VARCHAR(255) DEFAULT NULL,
  `spouse_birthdate` DATE DEFAULT NULL,
  `spouse_occupation` VARCHAR(255) DEFAULT NULL,
  `spouse_id_number` VARCHAR(100) DEFAULT NULL,
  `beneficiary_fn_1` VARCHAR(100) DEFAULT NULL,
  `beneficiary_ln_1` VARCHAR(100) DEFAULT NULL,
  `beneficiary_mi_1` VARCHAR(10) DEFAULT NULL,
  `beneficiary_birthdate_1` DATE DEFAULT NULL,
  `beneficiary_gender_1` CHAR(1) DEFAULT NULL,
  `beneficiary_relationship_1` VARCHAR(100) DEFAULT NULL,
  `beneficiary_dependent_1` TINYINT(1) NOT NULL DEFAULT 0,
  `beneficiary_fn_2` VARCHAR(100) DEFAULT NULL,
  `beneficiary_ln_2` VARCHAR(100) DEFAULT NULL,
  `beneficiary_mi_2` VARCHAR(10) DEFAULT NULL,
  `beneficiary_birthdate_2` DATE DEFAULT NULL,
  `beneficiary_gender_2` CHAR(1) DEFAULT NULL,
  `beneficiary_relationship_2` VARCHAR(100) DEFAULT NULL,
  `beneficiary_dependent_2` TINYINT(1) NOT NULL DEFAULT 0,
  `beneficiary_fn_3` VARCHAR(100) DEFAULT NULL,
  `beneficiary_ln_3` VARCHAR(100) DEFAULT NULL,
  `beneficiary_mi_3` VARCHAR(10) DEFAULT NULL,
  `beneficiary_birthdate_3` DATE DEFAULT NULL,
  `beneficiary_gender_3` CHAR(1) DEFAULT NULL,
  `beneficiary_relationship_3` VARCHAR(100) DEFAULT NULL,
  `beneficiary_dependent_3` TINYINT(1) NOT NULL DEFAULT 0,
  `beneficiary_fn_4` VARCHAR(100) DEFAULT NULL,
  `beneficiary_ln_4` VARCHAR(100) DEFAULT NULL,
  `beneficiary_mi_4` VARCHAR(10) DEFAULT NULL,
  `beneficiary_birthdate_4` DATE DEFAULT NULL,
  `beneficiary_gender_4` CHAR(1) DEFAULT NULL,
  `beneficiary_relationship_4` VARCHAR(100) DEFAULT NULL,
  `beneficiary_dependent_4` TINYINT(1) NOT NULL DEFAULT 0,
  `trustee_name` VARCHAR(255) DEFAULT NULL,
  `trustee_birthdate` DATE DEFAULT NULL,
  `trustee_relationship` VARCHAR(100) DEFAULT NULL,
  `member_name` VARCHAR(255) DEFAULT NULL,
  `sig_beneficiary_name` VARCHAR(255) DEFAULT NULL,
  `member_signature` VARCHAR(255) DEFAULT NULL,
  `beneficiary_signature` VARCHAR(255) DEFAULT NULL,
  `disclaimer_agreement` TINYINT(1) NOT NULL DEFAULT 1,
  `status` ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 